# Generated by Django 4.1.2 on 2022-10-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='random_string',
            field=models.CharField(default='VRZVvWceWr5CfXB387ASCQECy6rTT4OqoONUoK4wjyxR5qrjk9', max_length=50),
        ),
    ]
